"""
Markdown Documentation Generator

يقوم بتوليد توثيق فني بتنسيق Markdown نقي بدون أي HTML أو CSS.
التركيز على المحتوى المنطقي والتنسيق النصي البسيط فقط.
"""

import logging
from core_ai.ai_engine.doc.doc_generator import DocumentationGenerator
import datetime
logger = logging.getLogger(__name__)


class MarkdownGenerator(DocumentationGenerator):
   def _format_output(self, content, data):
        """
        تنسيق المحتوى كـ Markdown نقي مع الحفاظ على الهيكل الناتج من الـ Agents
        """
        content_str = str(content) if content else ""

        exp_type_display = "Technical Documentation"
        if data and data.get('explanation_type') == 'high_level':
            exp_type_display = "Executive Overview"
            
        created_at = datetime.datetime.now().strftime("%Y-%m-%d")
        
        filename = "UNKNOWN_MODULE"
        if data and data.get('filename'):
            filename = data.get('filename').upper()
        else:
            import re
            file_match = re.search(r'File:\s*([^\s\n]+)', content_str)
            if file_match:
                filename = file_match.group(1).upper()

        header = (
            f"# 📜 {filename}\n"
            f"> **STATUS:** ✅ VERIFIED | **DATE:** {created_at}\n"
            f"> **TYPE:** {exp_type_display}\n\n"
            f"---"
        )

        diagram = ""
        image_url = data.get('image_url', '') if data else ''
        if image_url:
            diagram = f"\n### 📊 Architecture Visualization\n![Class Diagram]({image_url})\n\n---\n"

        clean_content = re.sub(r'^File:.*?\n', '', content_str, flags=re.MULTILINE).strip()

        footer = (
            f"\n\n---\n"
            f"*Generated by **AutoTest & DocGen** | Technical Intelligence Unit*"
        )

        return f"{header}{diagram}\n\n{clean_content}{footer}"