"""
Django settings for Ai_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv  # 👈 أضف هذا السطر

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")

NOTIFICATION_SERVICE_URL = os.environ.get('NOTIFICATION_SERVICE_URL', 'http://notification_django_app:8000')

SERVICE_API_KEY = os.environ.get('AI_SERVICE_KEY', "sk-ai-project-2025-v3-e0d9b4f2a7c8e9d0b1f2a3c4e5d6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4") # 👈 من متغيرات البيئة# ...  


SECRET_KEY = os.environ.get('AI_DJANGO_SECRET_KEY', 'ai-project-secret-key-2025-v3-unique') # مفتاح منفصل للـ AI project

DEBUG = os.environ.get('DEBUG', 'True') == 'True' # من .env

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,ai_web,ai_django_app,web,upm_backend,upm_api_gateway,nginx,upm_django_app').split(',')

if 'ai_web' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('ai_web')

if DEBUG:
    ALLOWED_HOSTS = ['*'] 
    

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core_ai',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ai_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ai_project.wsgi.application'



DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3', # يمكن استخدام SQLite3 كقاعدة بيانات افتراضية إذا لم تكن هناك حاجة لقاعدة بيانات SQL
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

MONGO_HOST = os.environ.get('MONGO_HOST', 'localhost')  # localhost for local development
MONGO_PORT = int(os.environ.get('MONGO_PORT', 27017))
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'ai_mongodb_db')


CODE_FILES_COLLECTION = 'code_files'
ANALYSIS_JOBS_COLLECTION = 'analysis_jobs'
ANALYSIS_RESULTS_COLLECTION = 'analysis_results'
AI_EXPLANATIONS_COLLECTION = 'ai_explanations'
AI_TASKS_COLLECTION = 'ai_tasks'
DOCUMENTATION_FILES_COLLECTION = 'documentation_files'
GENERATED_FILES_COLLECTION = 'generated_files'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = '/static/ai/'
STATIC_ROOT= os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'

ADMIN_URL = 'admin/'  # مسار admin الداخلي

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

FORCE_SCRIPT_NAME = None
ADMIN_MEDIA_PREFIX = '/static/ai/admin/'

SESSION_COOKIE_NAME = 'ai_sessionid'
SESSION_COOKIE_AGE = 1209600  # أسبوعين
SESSION_COOKIE_SECURE = False  # False للـ HTTP
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True

CSRF_COOKIE_NAME = 'ai_csrftoken'
CSRF_COOKIE_SECURE = False  # False للـ HTTP
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = ['http://localhost', 'http://127.0.0.1']
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600  # سنة واحدة

CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
]
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
   'DEFAULT_AUTHENTICATION_CLASSES': (
       'rest_framework_simplejwt.authentication.JWTAuthentication', # إضافة هذا السطر
       'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
  ),
  'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # يمكن تغييرها حسب الحاجة
    ),
}

REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')  # localhost للتطوير، redis للـ Docker
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'redis://{REDIS_HOST}:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', f'redis://{REDIS_HOST}:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True


CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO', # أو DEBUG
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': { # هذا هو المهم لأخطاء 500
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'Ai_project.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'llm-cache',
        'TIMEOUT': 3600 * 24,  # 24 ساعة
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

LLM_RATE_LIMIT = {
    'MAX_REQUESTS_PER_DAY': 50,  # للحساب المجاني
    'CACHE_TIMEOUT': 3600 * 24,  # 24 ساعة
    'RETRY_AFTER_MINUTES': 60,   # انتظار ساعة بعد rate limit
}
